### PR TITLE
Set `$fixtureDataPath = '@tests/_data'`

### LINKED ISSUE #31: `$fixtureDataPath` should be '@tests/_data' as Codeception does
Codeception sets `protected $dataDir = 'tests/_data';` in [`src/Codeception/Template/Bootstrap.php`](https://github.com/Codeception/Codeception/blob/e3eba4c2bc1bec26c5270a0c780f95ab7ab4ea00/src/Codeception/Template/Bootstrap.php#L13):

```php
protected $dataDir = 'tests/_data';
```

and `yii2-app-basic` sets it in [`codeception.yml`](https://github.com/yiisoft/yii2-app-basic/blob/9245d033e4c1cc41aa1beabcd4564af497535ad0/codeception.yml#L5):

```yml
data: tests/_data
```

but `yii2-faker` sets `$fixtureDataPath` as `'@tests/unit/fixtures/data'`:

https://github.com/yiisoft/yii2-faker/blob/bc6238fc7478d0eb252ee7144d98b9c6e732ec55/FixtureController.php#L148

`yii2-faker` should sets `$fixtureDataPath = 'tests/_data'`, as Codeception does.

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.14
| PHP version      | 7.2.2-3+ubuntu16.04.1+deb.sury.org+1
| Operating system | Ubuntu 16.04.3 LTS

### PR DESCRIPTION
**Pull request by ricpelo**
Fixes #31.

| Q             | A
| ------------- | ---
| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | #31

### CODE REVIEW

**Comment by samdark** [comment]
I think there are docs using the old alias so if we're going to make this change, guide should be adjusted.

**Comment by ricpelo** [comment]
I'll try to locate them using `grep` or similar.

**Comment by ricpelo** [comment]
Aside from that, the optimal approach would be, obviously, to generate the data under `FixturePath/data/`, where `FixturePath` stands for the directory containing this fixture class, as [`$dataFile` property documentation](http://www.yiiframework.com/doc-2.0/yii-test-activefixture.html#$dataFile-detail) says.

**Comment by ricpelo** [comment]
I was unable to find any references to `@tests/unit/fixtures/data` because the guide incorrectly points to `@tests/unit/fixtures` instead. My last commit fixes that changing them to `@tests/_data`.

**Comment by ricpelo** [comment]
The more I look into it, the less I think this PR is interesting. IMO, documentation and code from yii2 & yii2-faker is messy about fixtures paths & namespaces. I'm going to close this PR by now and I'll try to prepare another PR which bring some global order.

**Pull request closed without merging**
